In [2]:
import numpy as np

#### 1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [66]:
a = np.arange(12, 24)
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23]


#### 2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [20]:
a1 = a.reshape(2, 6)
a2 = a.reshape(6, 2)
a3 = a.reshape(3, 4)
a4 = a.reshape(4, 3)
a5 = a.reshape(1, 12)
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13 14 15 16 17 18 19 20 21 22 23]]


#### 3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [22]:
a1 = a.reshape(-1, 6)
a2 = a.reshape(-1, 2)
a3 = a.reshape(-1, 4)
a4 = a.reshape(4, -1)
a5 = a.reshape(1, -1)
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13 14 15 16 17 18 19 20 21 22 23]]


#### 4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

Нельзя, так как там есть столбцы и строки.

#### 5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [36]:
a = np.random.randn(3, 4)
print(a)
b = a.flatten()
print("")
print(b)

[[-1.27874202  1.55607967  1.4363215   0.36696939]
 [ 1.15034947 -0.20978424 -1.39326819 -0.20388207]
 [ 1.32010961 -1.49796876 -0.37138849 -2.07887477]]

[-1.27874202  1.55607967  1.4363215   0.36696939  1.15034947 -0.20978424
 -1.39326819 -0.20388207  1.32010961 -1.49796876 -0.37138849 -2.07887477]


#### 6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [45]:
a = np.arange(20, 0, -2)
print(a)

[20 18 16 14 12 10  8  6  4  2]


#### 7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [55]:
b = a.reshape(1,10)

print(b)
## Массив a одномерный, b - двумерный

[[20 18 16 14 12 10  8  6  4  2]]


#### 8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [72]:
a = np.zeros((2,2))
b = np.ones((3,2))
v = np.concatenate((a, b), axis=0)
print(a)
print("")
print(b)
print("")
print(v)
print(f"size ab: {v.size}")

[[0. 0.]
 [0. 0.]]

[[1. 1.]
 [1. 1.]
 [1. 1.]]

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
size ab: 10


#### 9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [114]:
a = np.arange(0, 12)
A = a.reshape(4, 3)
At = A.T
B = A.dot(At)
print(a)
print(A)
print(At)
print(B)
print(f"size B: {B.size}")
print(f"Вычислить обратную матрицу для матрицы B невозможно так как её определитель равен {np.linalg.det(B)}")

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
size B: 16
Вычислить обратную матрицу для матрицы B невозможно так как её определитель равен 0.0


#### 10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [88]:
np.random.seed(42)

#### 11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [124]:
a = np.linspace(0, 15, 16)
print(a)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


#### 12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [130]:
C = a.reshape(4,4)
D = C*10 + B
det_D = np.linalg.det(D)
rank_D = np.linalg.matrix_rank(D)
D_inv = np.linalg.inv(D)
print(C)
print("")
print(D)
print(f"Определитель D: {det_D}")
print(f"Ранг D: {rank_D}")
print(D_inv)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]

[[  5.  24.  43.  62.]
 [ 54. 100. 146. 192.]
 [103. 176. 249. 322.]
 [152. 252. 352. 452.]]
Определитель D: 5.18953807259442e-26
Ранг D: 2
[[ 4.66062690e+13 -1.49229688e+13 -1.09972869e+14  7.82895692e+13]
 [ 1.63480451e+14 -3.81454387e+14  2.72467419e+14 -5.44934838e+13]
 [-4.66779710e+14  8.07677680e+14 -2.15016230e+14 -1.25881740e+14]
 [ 2.56692989e+14 -4.11300324e+14  5.25216801e+13  1.02085655e+14]]


#### 13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.